<?php

namespace app\util;
class UtilLang {
    public static $contents = [
        'tools'          => [
            'json_valid'         => 'JSON 数据合法',
            'json_error'         => 'JSON 数据错误:',
            'no_code'            => '文本框中没有代码！',
            'no_data'            => '请输入数据',
            'no_valid_unicode'   => '文本框中没有合法的Unicode代码！',
            'base_input'         => '转换数字',
            'base'               => '进制',
            'base_output'        => '转换结果',
            'md5_input'          => '加密文本：',
            'md5_output'         => '加密结果：',
            'sha_input'          => '加密文本：',
            'sha_output'         => '加密结果：',
            'json_collapse'      => '折叠节点',
            'json_root_collapse' => '根节点可折叠',
            'json_quotes'        => 'key添加双引号',
            'json_links'         => '链接可访问',
        ],
        'regex'          => [
            'flags'          => '修饰符',
            'number'         => '匹配数字',
            'char'           => '匹配字母',
            'chinese'        => '匹配中文',
            'syntax'         => '语法参考',
            'holder'         => '在此输入待匹配的文本',
            'replace'        => '替换文本',
            'flag_g'         => '全局搜索',
            'flag_i'         => '忽略大小写',
            'flag_m'         => '多行模式',
            'flag_s'         => '包含换行符',
            'summery'        => '共找到%s匹配：',
            'flags_select'   => "已选个数： ",
            'more'           => "更多正则",
            'more_email'     => "邮件地址",
            'more_url'       => 'URL地址',
            'more_telephone' => '国内电话',
            'more_id_card'   => '身份证号',
            'more_date'      => '年-月-日',
            'more_ip'        => 'IP 地址',
        ],
        'check'          => [
            'dkim'                => 'DKIM 记录发布',
            'dkim_ok'             => 'DKIM 记录找到',
            'dkim_err'            => 'DKIM 记录未找到',
            'dkim_syntax'         => 'DKIM 格式验证',
            'dkim_syntax_ok'      => 'DKIM 格式验证通过',
            'dkim_syntax_err'     => 'DKIM 格式验证错误',
            'dkim_public_key'     => 'DKIM 公钥验证',
            'dkim_public_key_ok'  => 'DKIM 公钥验证通过',
            'dkim_public_key_err' => 'DKIM 公钥验证错误',
            'dmarc'               => 'DMARC 记录发布',
            'dmarc_ok'            => 'DMARC 记录找到',
            'dmarc_err'           => 'DMARC 记录未找到',
            'dmarc_syntax'        => 'DMARC 格式验证',
            'dmarc_syntax_ok'     => 'DMARC 格式验证通过',
            'dmarc_syntax_err'    => 'DMARC 格式验证错误',
            'dmarc_qua'           => 'DMARC 策略启用',
            'dmarc_qua_ok'        => 'DMARC 隔离/拒绝 策略已启用',
            'dmarc_qua_err'       => 'DMARC 隔离/拒绝 策略未来启用',
        ],
        'smtp'           => [
            'connect'         => '连接至 %s',
            'con_err'         => '连接错误： %s',
            'err'             => '错误： %s',
            'relay'           => '可能是开放式转发邮件服务器',
            'domain_mismatch' => '反查域名和邮件服务器响应头域名不一致',
        ],
        'whois'          => [
            'reporter' => '来源：<span class="report_ip">%s</span>',
            'raw'      => '原数据',
        ],
        'page'           => [
            'login'    => '<p>请登录后查看</p><p><a href="#" type="button" class="layui-btn layui-btn-radius login-btn">登录</a></p>',
            'ptr'      => '<p>您的查询发生错误。 请再试一次。</p><br><p>输入无效。 PTR 查询需要 IP 地址。</p>',
            'domain'   => '<p>不是有效的域名或 IP 地址，请检查</p>',
            'throttle' => '<p>请求过多，请在 %s 秒后重试。</p>',
            'dkim'     => '<p>您的查找发生错误。 请重试。</p>
    <p>查询 DKIM 时必须包含选择器。</p><br>
    <p>选项 1：(域):(选择器)</p>
    <p>即 example.com:email - 其中 example.com 是域部分，email 是选择器，用冒号分隔</p><br>
    <p>选项 2：(选择器).(_domainkey).(domain) </p><p>即 email._domainkey.example.com - 其中 email 是选择器，后跟 ._domainkey。 然后 example.com 作为域。</p>',
            'health'   => '<p>发生错误。 请重试。</p>
    <p>未能未查询到 %s 的MX记录，可能域名下没有邮件服务，请检查域名MX记录存在。</p>',
        ],
        'page_type'      => [
            'dns_mx'               => 'MX 记录',
            'dns_a'                => 'A 记录',
            'dns_ptr'              => 'PTR 记录',
            'dns_ns'               => 'NS 记录',
            'dns_spf'              => 'SPF 记录',
            'dns_dkim'             => 'DKIM 记录',
            'dns_dmarc'            => 'DMARC 记录',
            'black_index'          => 'IP 黑名单',
            'util_whois'           => '域名Whois查询',
            'util_header'          => '邮件头分析',
            'util_health'          => '邮件健康分析',
            'tools_regex'          => '正则测试',
            'tools_json_converter' => 'JSON 转换',
            'tools_json'           => 'JSON 解析',
            'tools_base64'         => 'Base64 编码/解码',
            'tools_html'           => 'HTML 编码/解码',
            'tools_unicode'        => 'Unicode 编码/解码',
            'tools_url'            => 'URL 编码/解码',
            'tools_base'           => '进制转换',
            'tools_md5'            => 'MD5 加密',
            'tools_sha'            => 'SHA 加密',
        ],
        'analyze_header' => [
            'chart_title' => '延迟 (秒)',
            'delay'       => '接收延迟: %s 秒',
            'y_from'      => '从 %s ',
            'y_to'        => '到 ',
            'all_header'  => "全部头信息 ",
        ],
        'dmarc_tag_name' => [
            'v'     => '版本',
            'p'     => '策略',
            'rua'   => '接收者',
            'ruf'   => '取证接收者',
            'sp'    => '子域策略',
            'adkim' => 'DKIM 签名对齐',
            'aspf'  => 'SPF 对齐',
            'fo'    => '报告选项',
            'rf'    => '报个格式',
            'pct'   => '百分比',
            'ri'    => '报告间隔',
        ],
        'dmarc_tag_desc' => [
            'v'     => '版本标签。唯一允许的值为“DMARC1”。如果不正确或标签丢失，DMARC 记录将被忽略',
            'p'     => 'DMARC 政策。允许的值为“无”、“隔离”或“拒绝”。默认值为“无”，即不对未经身份验证的电子邮件采取任何操作。它仅有助于收集 DMARC 报告并深入了解您当前的电子邮件流及其身份验证状态。 “隔离”将失败的电子邮件标记为可疑，而“拒绝”则阻止它们。',
            'rua'   => '聚合报告发送目的地。这是 ESP 用于发送故障报告的“mailto:”URI。该标签是可选的，但如果跳过它，您将不会收到报告。',
            'ruf'   => '取证（失败）报告发送目的地。这是 ESP 用于发送故障报告的“mailto:”URI。该标签是可选的，但如果跳过它，您将不会收到报告。',
            'sp'    => '子域策略。除非此处特别定义，否则子域继承上面解释的域策略标记 (p=)。与域策略一样，允许的值为“无”、“隔离”或“拒绝”。该选项目前并未广泛使用。',
            'adkim' => 'DKIM 签名对齐。此标记遵循 DKIM 域和父标头发件人域之间的对齐方式。允许的值为“r”（宽松）或“s”（严格）。 “r”是默认值，允许部分匹配，而“s”标签要求域相同。',
            'aspf'  => 'SPF 对齐。此标记遵循 SPF 域（发件人）和标头发件人域之间的对齐。允许的值为“r”（宽松）或“s”（严格）。 “r”是默认值，允许部分匹配，而“s”标签要求域完全相同。',
            'fo'    => '取证报告选项。允许的值为“0”、“1”、“d”和“s”。 “0”是默认值，当 SPF 和 DKIM 均无法生成对齐通道时，该值会生成取证报告。如果任一协议结果不是通过，则使用“1”。当 DKIM 无效时，“d”生成报告，而“s”对 SPF 执行相同的操作。定义 ruf 标签以接收取证报告。',
            'rf'    => '故障报告的报告格式。允许的值为“afrf”和“iodef”。',
            'pct'   => '百分比标签。此标记仅适用于具有“隔离”或“拒绝”策略的域。它标记了应应用给定策略的失败电子邮件的百分比。其余的则属于较低的政策。例如，如果“pct=70”，在具有“隔离”策略的域上，则仅在 70% 的情况下适用。剩下的 30% 属于“p=none”。同样，如果“p=reject”且“pct=70”，则“拒绝”适用于 70% 的失败电子邮件，而 30% 则进入“隔离”。',
            'ri'    => '报告间隔。标记接收 XML 报告的频率（以秒为单位）。默认值为 86400（每天一次）。无论设置的时间间隔如何，在大多数情况下，ISP 都会以不同的时间间隔（通常每天一次）发送报告。',
        ],
        'spf_prefix'     => [
            '+' => '通过',
            '-' => '失败',
            '~' => '软失败',
        ],
        'spf_desc'       => [
            'v'       => 'SPF 记录版本',
            'include' => "在指定域中搜索“允许”.",
            'mx'      => '如果 IP 是给定域名的 MX 主机之一，则匹配。',
            'ip4'     => '如果 IP 在给定范围内则匹配。',
            'ip6'     => '如果 IP 在给定范围内则匹配。',
            'ptr'     => "如果 IP 在给定域内具有 DNS“PTR”记录，则匹配。",
            'all'     => '总是匹配。它出现在你的记录的末尾。',
        ],
        'dkim_tag_name'  => [
            'v'  => '版本',
            'p'  => '公钥',
            'k'  => '钥匙类型',
            'n'  => '可选评论',
            'd'  => 'SDID值',
            'bh' => '正文哈希',
            'a'  => '签名算法',
            's'  => '选择器',
            'c'  => '归一化算法',
            'q'  => '默认查询方式',
            'i'  => 'AUID',
            't'  => '时间戳',
            'x'  => '到期日',
            'l'  => '体长',
            'h'  => '哈希算法',
            'z'  => '标头字段',
            'b'  => '签名',
        ],
        'dkim_tag_desc'  => [
            'v'  => '版本标签指示 DKIM 的版本，应始终设置为 1。',
            'p'  => '该标签值在以 Base64 编码之前的语法和语义由 (k) 标签定义。',
            'k'  => '标签 (p) 使用的密钥类型。',
            'd'  => 'SDID 声称负责将消息引入邮件流。',
            'bh' => '消息的规范化正文部分的哈希值受 \'l=\' 标签限制。',
            'n'  => '管理员可选的注释字段。',
            'a'  => '签名算法',
            's'  => '选择器',
            't'  => '签名时间戳',
            'h'  => '标头字段 - 已签名的字段列表',
            'c'  => '标头和正文的规范化算法',
            'q'  => '默认查询方式',
            'i'  => '代理或用户标识符 (AUID)',
            'x'  => '过期时间',
            'l'  => '体长',
            'z'  => '标头字段 - 所选标头字段和值的副本',
            'b'  => '标头和正文的签名',
        ],
        'table_headers'  => [
            'mname'        => '主服务器',
            'rname'        => '管理员',
            'serial'       => '序列号',
            'refresh'      => '刷新时长(秒)',
            'retry'        => '重试时长(秒)',
            'expire'       => '过期时长(秒)',
            'minimum'      => '最小生命期(秒)',
            'preference'   => '优先级',
            'exchange'     => '地址',
            'type'         => '类型',
            'ttl'          => '生命期',
            'ip'           => 'IP地址',
            'ops'          => '操作',
            'prefix'       => '前缀',
            'prefixdesc'   => '前缀描述',
            'description'  => '描述',
            'value'        => '值',
            'issue'        => '问题',
            'tag'          => '标签',
            'tagvalue'     => '值',
            'ptrdname'     => '域名',
            'name'         => '名称',
            'nsdname'      => '地址',
            'address'      => '地址',
            'class'        => '类别',
            'status'       => '状态',
            'blacklist'    => '黑名单',
            'blacklists'   => '黑名单',
            'reason'       => '原因',
            'header_name'  => '名称',
            'header_value' => '值',
            'hop'          => '时序',
            'delay'        => '延迟',
            'from'         => '发出',
            'by'           => '目标',
            'with'         => '使用',
            'id'           => 'ID',
            'time'         => '时间',
            'host'         => '域名',
            'test'         => '测试',
            'result'       => '结果',
        ],
        'dns'            => [
            'no_record'    => "%s 记录未找到，域名/IP: %s",
            'record_found' => "%s 记录，域名/IP: %s",
            'reporter'     => '来源于： <span class="report_ip">%s</span> (%s) ',
            'not_found'    => '未查询到记录 或 查询失败'
        ],
        'common'         => [
            'collapsible'       => '折叠/展开',
            'domain'            => '域名',
            'domainorip'        => '域名 或 IP',
            'ip'                => 'IP',
            'lookup'            => '查询',
            'setting'           => '设置',
            'check'             => '检查',
            'blacklist'         => '黑名单',
            'header'            => '邮件头信息',
            'use_server'        => '指定地址：',
            'use_server_server' => '查询地址：',
            'use_server_tld'    => 'TLD：',
            'seconds'           => ' 秒',
            'black_ok'          => ' 未列入',
            'black_listed'      => ' 被列入',
            'black_err'         => ' 被列入',
            'black_timeout'     => ' 超时',
            'status_ok'         => ' 正常',
            'status_err'        => ' 错误',
            'status_timeout'    => ' 超时',
            'dkim_p_record'     => 'DKIM 公开记录',
            'dkim_signature'    => 'DKIM 签名:',
            'loading'           => '查询中',
            'diagnostics'       => '连接测试',
            'mail_server'       => '邮件服务器',
            'server'            => '服务器: ',
            'or'                => '或',
            'regex'             => '正则表达式',
            'copied'            => '已复制',
            'lang'              => '语言',
        ],
        'button'         => [
            'black_check'   => '检查黑名单',
            'smtp_check'    => '检查连接',
            'analyze'       => '分析',
            'login'         => '登录',
            'register'      => '注册',
            'forget'        => '忘记密码 ?',
            'replace'       => '替换',
            'format'        => '格式化',
            'minify'        => '压缩',
            'verify'        => '验证',
            'json2xml'      => 'JSON 转 XML',
            'json2csv'      => 'JSON 转 CSV',
            'json2yaml'     => 'JSON 转 YAML',
            'json_tutorial' => 'JSON 教程',
            'encode'        => '编码',
            'decode'        => '解码',
            'copy'          => '复制',
            'clear'         => '清空',
            'u2h'           => 'Unicode 转 中文',
            'h2u'           => '中文 转 Unicode',
            'a2u'           => 'ASCII 转 Unicode',
            'u2a'           => 'Unicode 转 ASCII',
            'encrypt'       => '加密',
            'parse'         => '解析',
        ],
        'index'          => [
            'menu_index'          => '首页',
            'menu_dns'            => 'DNS 查询',
            'menu_mx'             => 'MX 记录查询',
            'menu_spf'            => 'SPF 记录查询',
            'menu_dmarc'          => 'DMARC 记录查询',
            'menu_dkim'           => 'DKIM 记录查询',
            'menu_ns'             => 'NS 记录查询',
            'menu_a'              => 'A 记录查询',
            'menu_ptr'            => 'PTR 记录查询',
            'menu_soa'            => 'SOA 记录查询',
            'menu_blacklists'     => 'IP黑名单',
            'menu_whois'          => 'Whois 查询',
            'menu_analyze'        => '邮件头分析',
            'menu_smtp'           => '连接测试',
            'menu_server'         => '邮件服务器',
            'menu_health'         => '邮件健康',
            'menu_tool'           => '常用工具',
            'menu_regex'          => '正则测试',
            'menu_base64'         => 'Base64 编/解码',
            'menu_html'           => 'HTML 编/解码',
            'menu_json_converter' => 'JSON 转换',
            'menu_json'           => 'JSON 解析',
            'menu_unicode'        => 'Unicode 编/解码',
            'menu_base'           => '进制转换',
            'menu_url'            => 'URL 编/解码',
            'menu_md5'            => 'MD5 加密',
            'menu_sha'            => 'SHA 加密',
            'lang_cn'             => '中文',
            'lang_en'             => 'English',
            'account'             => '邮箱地址',
            'password'            => '密码',
            'captcha'             => '验证码',
        ],
        'ip'             => [
            'empty' => 'IP地址为空',
        ],
        'require'        => [
            'domain' => '请输入域名',
        ],
        'err'            => [
            'op'       => '操作失败',
            'request'  => '请求错误',
            'no_auth'  => '无权限',
            'params'   => '参数错误',
            'system'   => '系统错误',
            '404'      => '404',
            'empty_ip' => 'IP 地址解析失败',
        ],
        'help'           => [
            'index' => '帮助中心'
        ],
    ];
    public static function get($name) {
        return self::$contents[$name];
    }

}